### ISSUE TITLE
Failed to run examples

### ISSUE THREAD

**Issue by jason-yau** [SamRodri/zng#180] opened 2024-05-03 19:59 UTC
See image below
<img width="1761" alt="image" src="https://github.com/zng-ui/zng/assets/91023929/32a85d92-a7be-4b6d-9427-d91f7616db2a">

**Comment by SamRodri** [comment] 2024-05-03 20:19
Thanks for checking out zng! 

breakpad-sys built ok in the Mac CI 3 days ago.

I don't have access to a Mac right now, can you try running this [upstream example,](https://github.com/EmbarkStudios/sentry-contrib-rust/blob/main/breakpad-handler/examples/handle_crash.rs) see if it builds?

**Comment by SamRodri** [comment] 2024-05-04 11:09
I cannot reproduce the issue, Google found one other instance of it happening however, [fixed by updating your system maybe](https://github.com/firebase/flutterfire/issues/11936#issuecomment-1828587986).

You could also try building without the "crash_handler" cargo feature, it is enabled by default, the `examples/Cargo.toml` defines the deps for all examples.

**Comment by SamRodri** [comment] 2024-05-12 13:26
Added a README note for macOS (#197). If updating your system does not fix the issue leave a comment and I will reopen it.

**Closed as completed by SamRodri** 2024-05-12 13:26 UTC
Labels: O-macos, A-crash-handler
